FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
COPY jsconfig.json ./
RUN npm ci
COPY . .
# Wir benutzen RELATIVE API-URL, weil Nginx /api weiterleitet
ARG REACT_APP_API_URL=/api
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
RUN npm run build

FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
