FROM node:20-alpine AS build
WORKDIR /app

RUN npm run build
RUN npm config set fund false && npm config set audit false

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm \
    if [ -f package-lock.json ]; then \
      npm ci --verbose || npm install --legacy-peer-deps --verbose; \
    else \
      npm install --legacy-peer-deps --verbose; \
    fi

COPY . .


FROM nginx:alpine
COPY --from=build /app/build/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
